// <auto-generated />
using DataSurvey.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataSurvey.Migrations
{
    [DbContext(typeof(SurveyContext))]
    [Migration("20251204155151_inital")]
    partial class inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataSurvey.Models.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorId"));

                    b.Property<bool>("CulinaryArts")
                        .HasColumnType("bit");

                    b.Property<bool>("CyberSecurity")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Programming")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Welding")
                        .HasColumnType("bit");

                    b.HasKey("InstructorId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            InstructorId = 1,
                            CulinaryArts = false,
                            CyberSecurity = false,
                            Email = "tpowell@smartweb.augustatech.edu",
                            Name = "Tenario Powell",
                            Password = "password1",
                            Programming = true,
                            Username = "tpowell",
                            Welding = false
                        },
                        new
                        {
                            InstructorId = 2,
                            CulinaryArts = true,
                            CyberSecurity = false,
                            Email = "abrown@smartweb.augustatech.edu",
                            Name = "Alton Brown",
                            Password = "password2",
                            Programming = false,
                            Username = "abrown",
                            Welding = false
                        },
                        new
                        {
                            InstructorId = 3,
                            CulinaryArts = false,
                            CyberSecurity = true,
                            Email = "skiddy@smartweb.augustatech.edu",
                            Name = "Script Kiddy",
                            Password = "password3",
                            Programming = false,
                            Username = "skiddy",
                            Welding = false
                        },
                        new
                        {
                            InstructorId = 4,
                            CulinaryArts = false,
                            CyberSecurity = false,
                            Email = "wone@smartweb.augustatech.edu",
                            Name = "Weld One",
                            Password = "password4",
                            Programming = false,
                            Username = "wone",
                            Welding = true
                        },
                        new
                        {
                            InstructorId = 5,
                            CulinaryArts = false,
                            CyberSecurity = false,
                            Email = "pinstructor@smartweb.augustatech.edu",
                            Name = "Programming Instructor",
                            Password = "password5",
                            Programming = true,
                            Username = "pinstructor",
                            Welding = false
                        },
                        new
                        {
                            InstructorId = 6,
                            CulinaryArts = false,
                            CyberSecurity = false,
                            Email = "winstructor@smartweb.augustatech.edu",
                            Name = "Welding Instructor",
                            Password = "password6",
                            Programming = true,
                            Username = "jshurling",
                            Welding = false
                        },
                        new
                        {
                            InstructorId = 7,
                            CulinaryArts = false,
                            CyberSecurity = true,
                            Email = "cinstructor@smartweb.augustatech.edu",
                            Name = "CyberSecurity Instructor",
                            Password = "password7",
                            Programming = false,
                            Username = "cyinstructor",
                            Welding = false
                        },
                        new
                        {
                            InstructorId = 8,
                            CulinaryArts = true,
                            CyberSecurity = false,
                            Email = "cainstructor@smartweb.augustatech.edu",
                            Name = "CulinaryArts Instructor",
                            Password = "password8",
                            Programming = false,
                            Username = "cainstructor",
                            Welding = false
                        });
                });

            modelBuilder.Entity("DataSurvey.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<bool>("CulinaryArts")
                        .HasColumnType("bit");

                    b.Property<bool>("CyberSecurity")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Programming")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Welding")
                        .HasColumnType("bit");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 900000001,
                            CulinaryArts = false,
                            CyberSecurity = false,
                            Email = "jshurling@smartweb.augustatech.edu",
                            Name = "Jack Shurling",
                            Password = "password1",
                            Programming = true,
                            Username = "jshurling",
                            Welding = false
                        },
                        new
                        {
                            StudentId = 900000002,
                            CulinaryArts = true,
                            CyberSecurity = true,
                            Email = "jdoe@smartweb.augustatech.edu",
                            Name = "Jane Doe",
                            Password = "password2",
                            Programming = true,
                            Username = "jdoe",
                            Welding = false
                        },
                        new
                        {
                            StudentId = 900000003,
                            CulinaryArts = true,
                            CyberSecurity = false,
                            Email = "johndoe@smartweb.augustatech.edu",
                            Name = "John Doe",
                            Password = "password3",
                            Programming = false,
                            Username = "jdoe1",
                            Welding = true
                        },
                        new
                        {
                            StudentId = 900000004,
                            CulinaryArts = false,
                            CyberSecurity = true,
                            Email = "ljames@smartweb.augustatech.edu",
                            Name = "Lebron James",
                            Password = "password4",
                            Programming = true,
                            Username = "ljames",
                            Welding = false
                        },
                        new
                        {
                            StudentId = 900000005,
                            CulinaryArts = true,
                            CyberSecurity = false,
                            Email = "wwonka@smartweb.augustatech.edu",
                            Name = "Willy Wonka",
                            Password = "password5",
                            Programming = true,
                            Username = "wwonka",
                            Welding = false
                        },
                        new
                        {
                            StudentId = 900000006,
                            CulinaryArts = false,
                            CyberSecurity = true,
                            Email = "flast@smartweb.augustatech.edu",
                            Name = "First Last",
                            Password = "password6",
                            Programming = false,
                            Username = "flast",
                            Welding = false
                        },
                        new
                        {
                            StudentId = 900000007,
                            CulinaryArts = false,
                            CyberSecurity = false,
                            Email = "wstudent@smartweb.augustatech.edu",
                            Name = "Welding Student",
                            Password = "password7",
                            Programming = false,
                            Username = "wstudent",
                            Welding = true
                        },
                        new
                        {
                            StudentId = 900000008,
                            CulinaryArts = true,
                            CyberSecurity = false,
                            Email = "gramsey@smartweb.augustatech.edu",
                            Name = "Gordon Ramsey",
                            Password = "password8",
                            Programming = false,
                            Username = "gramsey",
                            Welding = false
                        },
                        new
                        {
                            StudentId = 900000009,
                            CulinaryArts = false,
                            CyberSecurity = false,
                            Email = "oideas@smartweb.augustatech.edu",
                            Name = "Outta Ideas",
                            Password = "password9",
                            Programming = true,
                            Username = "oideas",
                            Welding = true
                        },
                        new
                        {
                            StudentId = 900000010,
                            CulinaryArts = true,
                            CyberSecurity = true,
                            Email = "oachiever@smartweb.augustatech.edu",
                            Name = "Over Achiever",
                            Password = "password10",
                            Programming = true,
                            Username = "oachiever",
                            Welding = true
                        });
                });

            modelBuilder.Entity("DataSurvey.Models.Survey", b =>
                {
                    b.Property<int>("PId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PId"));

                    b.Property<bool>("InstructorSurvey")
                        .HasColumnType("bit");

                    b.Property<bool>("StudentSurvey")
                        .HasColumnType("bit");

                    b.Property<string>("SurveyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurveyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PId");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("DataSurvey.Models.SurveyOptions", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OptionId"));

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurveyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OptionId");

                    b.ToTable("SurveyOptions");
                });

            modelBuilder.Entity("DataSurvey.Models.SurveyResponses", b =>
                {
                    b.Property<string>("SurveyResponsesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OptionId")
                        .HasColumnType("int");

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurveyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SurveyResponsesId");

                    b.ToTable("SurveyResponses");
                });
#pragma warning restore 612, 618
        }
    }
}
